version: '3.7'
services:
  minio:
    image: minio/minio
    volumes:
      - ./start-minio.sh:/start-minio.sh
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000" # Minio server port
      - "9001:9001" # Minio console port (browser access)
    entrypoint: ["/bin/sh", "/start-minio.sh"]

volumes:
  minio_data: