# Generated by Django 4.2.7 on 2023-11-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(choices=[('X', 'X/Twitter'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagrm'), ('REDDIT', 'Rddit')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField()),
                ('post_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('post_image', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_prediction', models.CharField(max_length=255)),
                ('classifier_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.classifierresponse')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.platform')),
            ],
        ),
        migrations.AddField(
            model_name='classifierresponse',
            name='Label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.label'),
        ),
    ]
