# Generated by Django 4.2.7 on 2024-01-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassifierResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(max_length=255, unique=True)),
                ("reporting_link", models.CharField(default="unknown", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_content", models.TextField()),
                ("post_link", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "post_image",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "user_prediction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classifier_response",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="report.classifierresponse",
                    ),
                ),
                (
                    "post_platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="report.platform",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classifierresponse",
            name="Label",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="report.label",
            ),
        ),
    ]
