# Generated by Django 4.2.7 on 2024-01-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial_populate'),
        ('report', '0002_platform_reporting_link'),
    ]

    operations = [
    ]
