# Generated by Django 4.2.7 on 2023-11-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Researcher',
        ),
    ]
